### ISSUE TITLE
Container support for gluon-nlp 

### ISSUE THREAD

**Issue by opringle** [aws/sagemaker-mxnet-training-toolkit#31]
Thinking of contributing a docker image with support for [gluonnlp](http://gluon-nlp.mxnet.io/) & GPU training. This relies on the most recent version of MXNet and cuda 9.2.

**Comment by iquintero** [comment]
Hi @opringle 

We can reconsider accepting a gluon-nlp contribution after we have support for MXNet 1.3 which we dont have an ETA for yet. In general we don't want to maintain another set of images (we already have 4 MXNet official images), If there is enough interest for this we can consider adding it to our official roadmap and perhaps be part of our official image. 

Otherwise, feel free to create a fork if you are doing it for your own use and feel like it could help others right away. If it is based on our mxnet-container then it should be compatible with our MXNet estimator.

Im going to leave this issue open as a feature request to help gauge interest in gluon-nlp :)

**Comment by vlordier** [comment]
hi @iquintero : there IS interest to integrate gluon-nlp and gluon-cv :)

**Comment by eric-haibin-lin** [comment]
Any update on this?

**Comment by laurenyu** [comment]
The Dockerfiles have now been moved to https://github.com/aws/deep-learning-containers.
